### PR TITLE
patricklodder's gitian sigs for 1.14.7

### PR DESCRIPTION
**Pull request by patricklodder**

### CODE REVIEW

**Comment by KunNw0n** [comment]
@patricklodder, any chance this PR to be merged ?

**Comment by patricklodder** [comment]
Anyone but I can merge it, so you're asking the wrong person. Maybe @chromatic wants to merge it :-)

**Comment by chromatic** [comment]
I'm happy to merge this, though I think we should document how to verify signatures in this repository. I know it's sort of in the Gitian documentation, but we give more people the chance to contribute by making our processes more explicit.

**Comment by patricklodder** [comment]
Agreed. Noting that if the universe agrees that after a decade, this should block my personal attestation to be on the master branch then I guess I better get to work on that 😂

**Comment by patricklodder** [comment]
@chromatic: README enhancement proposed to unblock this.

**Review by chromatic — APPROVED** [review]
ACK, verified--and with #37 now everyone knows how I verified and doesn't have to trust me blindly.

**Review by Skandiakiwi13 — APPROVED** [review]
Looks good to me

**Review by Skandiakiwi13 — APPROVED** [review]
Will come back to them

**Review by Skandiakiwi13 — COMMENTED** [review]
Looks good to me

**Review by Brooksie18 — COMMENTED** [review]
I hope I did everything correctly

**Pull request merged**
